### PR TITLE
Update code to the latest JDA versions

### PR DESCRIPTION
**Pull request by NathanEdg**
# Purpose of the PR
This pull request is meant to make this library usable on the latest version of JDA (v5.0.0-beta.20) and translate old code to new code. The PR also adds null checks and removes bots from the transcript as they cause issues.

## Changes
As highlighted above, the PR converts TextChannel and the file-sending methods to newer technology. The method of getting the template.html has changed as well. 

## Why is this necessary 
This upgrade makes this library usable by modern discord bots. 

## Additions
There is also a new method to return a FileUpload object to hold the transcript as a variable for later use.

### CODE REVIEW

**Comment by QuadrixYT** [comment]
@Ryzeon bump

**Comment by Ryzeon** [comment]
ty bro <3

**Comment by QuadrixYT** [comment]
I looked at jitpack and see an error with the build I will fix it today and will ping you again then you can publish with 1.1 or 1.2

**Comment by Ryzeon** [comment]
Fixed 👍🏼

**Pull request merged**
